name: github-actions
on:
  workflow_dispatch:

jobs:
  selenium:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'
      - run: |
          python -m pip install --upgrade pip
          pip install get-chrome-driver --upgrade
          pip install python-dotenv==0.19.2
          pip install selenium==3.141.0
          pip install tweepy==4.6.0
          pip install pillow==8.4.0
          pip install opencv-python==4.5.5.64
          python image.py
      - uses: actions/upload-artifact@v2
        with:
          name: image_save
          path: ./now.png
